<a href="https://colab.research.google.com/github/dubanmojica/programacion1/blob/main/Copia_de_Untitled17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

manejo de modulos integrados

modulos:
numpy: para base numericas calculos numericos.
pandas: para estructura de datos (tablas, bases de datos)

In [ ]:
import numpy as np

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4 ])
b = np.array([[1, 2], [3, 4], [5, "a"]])
print (a)
print (b)

[1 2 3 4]
[['1' '2']
 ['3' '4']
 ['5' 'a']]


In [ ]:
lista = [1, 2, 3, 4]
arr = np.array([1, 2, 3])

In [ ]:
lista*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
arr*2 #hay una interpretacion de los arreglos de tipo numpy mas apegados a lo que vemos en los objetos matematicos como los vectores

array([2, 4, 6])

In [ ]:
arr.shape

(3,)

In [ ]:
b.shape #arreglo de tres componenetes cada uno con dos elementos

(3, 2)

In [ ]:
arr.ndim

1

In [ ]:
b.ndim # numero de elementos por cada componenete

2

In [ ]:
a.ndim

1

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('<U21')

In [ ]:
b.size #cantidad de elemento en todas las componenentes

6

In [ ]:
np.zeros((2, 3)) #todo lleno de ceros: 2 componenetes y 3 elemtos por componenetes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(3) # la matriz identidad de una matriz cuadrada de tamaño 3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.arange(0, 10, 2) #del 0 hasta el 10 (sin tomar el 10) separado por 2

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0,1,5) #5 elemntos equidistantes entre el 0 y el 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

indexacion

In [ ]:
arry = np.array ([10, 20, 30, 40])
arry[-1]

np.int64(40)

In [ ]:
arry[-1]

np.int64(40)

In [ ]:
arry[0:2] #tomando el indice 0 al 2 (sin tomar el 2)

array([10, 20])

In [ ]:
matri = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
matri[:,0]

array([1, 4])

In [ ]:
matri[1,:]

array([4, 5, 6])

In [ ]:
matri[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(b[0,1], b[:1], b[1:])

2 [['1' '2']] [['3' '4']
 ['5' 'a']]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [ ]:
a * b #producto de hadamard entre dos arreglos

array([ 4, 10, 18])

In [ ]:
matri1 = np.array([[1, 2, 3], [3, 4, 5]])
matri1* matri #producto de hadamard

array([[ 1,  4,  9],
       [12, 20, 30]])

In [ ]:
[x * 2 for x in lista]

[2, 4, 6, 8]

In [ ]:
c = np.array([1.65, 1.58, 1.82, 1.70, 1.50, 1.82, 1.74])
print(np.mean(c), np.median(c), np.std(c), np.sum(c), np.min(c), np.max(c))

1.6871428571428573 1.7 0.11093296376181246 11.81 1.5 1.82


manipulacion de los arreglos

In [ ]:
d = np.array([1,2,3,4,5,6])#inicialmente tiene 6 componenetes de un elemnetoo cada una
d.reshape(2,3)#cambia a 2 componenetes cada una de 3 elementos

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([d, a])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [ ]:
np.concatenate(d.reshape(2,3))

array([1, 2, 3, 4, 5, 6])

In [ ]:
d.reshape(2,3).flatten() #vetoriza la matriz

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([[1, 2,], [4, 5,]])
b = np.array([[7, 8,], [10, 11,]])
np.dot(a, b)

array([[27, 30],
       [78, 87]])

In [ ]:
np.linalg.inv(a)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [ ]:
np.linalg.matrix_transpose(a)

array([[1, 4],
       [2, 5]])

In [ ]:
np.random.rand(10)# genera 10 valores de una distribucion uniforme en el inervalo(0,1)

array([0.76045492, 0.41048307, 0.47945785, 0.56422326, 0.7220108 ,
       0.7221706 , 0.81215997, 0.99378756, 0.37318806, 0.76722515])

In [ ]:
np.random.randint(0,10)#genetra un valor entre el 0 y el valor anterior al 10

4

In [ ]:
np.random.randn(8)# genera 8 valores aleatorios de una distribucion normal con media 0 y desviacion estandar 1

array([ 1.19075373, -1.89318165,  0.29199822, -0.94370124, -0.40722431,
        0.11969954,  0.14810572, -0.30389318])

In [ ]:
e = np.array([1,2,3,4,5])
f = e[e > 3]
f

array([4, 5])

In [ ]:
e[(e > 2) & (e < 5)] #note que el "y" es asi &. el "o" es asi

array([3, 4])

In [ ]:
np.where( e > 3, 1, 0) $donde e > 3 anotamos 1 donde no, un 0

array([0, 0, 0, 1, 1])

In [ ]:
np.where( e > 3, 1, e)

array([1, 2, 3, 1, 1])

In [ ]:
arreglo = np.arange(1, 11)

In [ ]:
arreglo*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
arreglo > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
t = np.array(arreglo)
p = t(t > 5)
p

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
t = np.array(arreglo)
p = t[t > 5]
p

array([ 6,  7,  8,  9, 10])

In [ ]:
c = np.arange(1, 10).reshape(3,3)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(np.mean(arreglo))
print(np.std(arreglo))

5.5
2.8722813232690143


In [ ]:
condicional = np.where(arreglo > 5, 1, 0)
condicional

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

PANDAS

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([10, 20, 30])
s

,0
0,10
1,20
2,30


In [ ]:
df = pd.DataFrame({
    'nombre': ['Ana', 'Luis', 'Carlos', 'Marta'],
    'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá'],
    'edad': [23, 30, 35, 28],
    'salario': [1500, 2000, 3000, 2500]
}) # creando data.frames
df

,nombre,ciudad,edad,salario
0,Ana,Bogotá,23,1500
1,Luis,Medellín,30,2000
2,Carlos,Cali,35,3000
3,Marta,Bogotá,28,2500


In [ ]:
df.head(2)

,nombre,ciudad,edad,salario
0,Ana,Bogotá,23,1500
1,Luis,Medellín,30,2000


In [ ]:
df.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   nombre   4 non-null      object
 1   ciudad   4 non-null      object
 2   edad     4 non-null      int64 
 3   salario  4 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes


In [ ]:
df.describe()# estadisticas descriptivas basicas para variables cuantitativas

,edad,salario
count,4.000000,4.000000
mean,29.000000,2250.000000
std,4.966555,645.497224
min,23.000000,1500.000000
25%,26.750000,1875.000000
50%,29.000000,2250.000000
75%,31.250000,2625.000000
max,35.000000,3000.000000


In [ ]:
df.shape

(4, 4)

In [ ]:
df["edad"] #para imprimiri la columna

,edad
0,23
1,30
2,35
3,28


In [ ]:
df[["nombre", "edad"]]

,nombre,edad
0,Ana,23
1,Luis,30
2,Carlos,35
3,Marta,28


In [ ]:
df[df["edad"] > 25]

,nombre,ciudad,edad,salario
1,Luis,Medellín,30,2000
2,Carlos,Cali,35,3000
3,Marta,Bogotá,28,2500


In [ ]:
df[(df["edad"] > 20) & (df["edad"] < 40) ]


,nombre,ciudad,edad,salario
0,Ana,Bogotá,23,1500
1,Luis,Medellín,30,2000
2,Carlos,Cali,35,3000
3,Marta,Bogotá,28,2500


In [ ]:
data = {
    'nombre': ['Ana', 'Luis', 'Carlos', 'Ana', None],
    'edad': [23, np.nan, 35, 23, 40],
    'salario': [1000, 2000, None, 1000, 5000],
    'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali']
}
data

{'nombre': ['Ana', 'Luis', 'Carlos', 'Ana', None],
 'edad': [23, nan, 35, 23, 40],
 'salario': [1000, 2000, None, 1000, 5000],
 'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali']}

In [ ]:
data1 = pd.DataFrame(data)
data1

,nombre,edad,salario,ciudad
0,Ana,23.0,1000.0,Bogotá
1,Luis,NaN,2000.0,Medellín
2,Carlos,35.0,NaN,Cali
3,Ana,23.0,1000.0,Bogotá
4,None,40.0,5000.0,Cali


In [ ]:
data1.isnull() #muestra true si falta algun valor y false si no

,nombre,edad,salario,ciudad
0,False,False,False,False
1,False,True,False,False
2,False,False,True,False
3,False,False,False,False
4,True,False,False,False


In [ ]:
data1.isnull().sum() #suma los valores por columna 1 si es faltante y 0 si no

,0
nombre,1
edad,1
salario,1
ciudad,0


In [ ]:
data2 = data1.dropna() #elimina las filas con valores faltantes
data2

,nombre,edad,salario,ciudad
0,Ana,23.0,1000.0,Bogotá
3,Ana,23.0,1000.0,Bogotá


In [ ]:
data1.dropna(subset=["salario"]) # se eleiminan las filas con valores faltantes unicamente en la columna salario

,nombre,edad,salario,ciudad
0,Ana,23.0,1000.0,Bogotá
1,Luis,NaN,2000.0,Medellín
3,Ana,23.0,1000.0,Bogotá
4,None,40.0,5000.0,Cali


In [ ]:
data1["edad"]=data1["edad"].fillna(data1["edad"].mean())
data1["nombre"]=data1["nombre"].fillna("desconocido")
data1

,nombre,edad,salario,ciudad
0,Ana,23.00,1000.0,Bogotá
1,Luis,30.25,2000.0,Medellín
2,Carlos,35.00,NaN,Cali
3,Ana,23.00,1000.0,Bogotá
4,desconocido,40.00,5000.0,Cali


In [ ]:
data1['ciudad'] = data1['ciudad'].replace('Bogotá', 'BOGOTA')
data1

,nombre,edad,salario,ciudad
0,Ana,23.00,1000.0,BOGOTA
1,Luis,30.25,2000.0,Medellín
2,Carlos,35.00,NaN,Cali
3,Ana,23.00,1000.0,BOGOTA
4,desconocido,40.00,5000.0,Cali


In [ ]:
data4 = data1["ciudad"].drop_duplicates()
data4

,ciudad
0,BOGOTA
1,Medellín
2,Cali


In [ ]:
data5 = {
    'nombre': ['Ana', 'Luis', 'Ana', 'Carlos', 'Luis'],
    'edad': [23, 30, 23, 35, 30],
    'ciudad': ['Bogotá', 'Cali', 'Bogotá', 'Medellín', 'Cali']
}
data5 = pd.DataFrame(data5)
data5

,nombre,edad,ciudad
0,Ana,23,Bogotá
1,Luis,30,Cali
2,Ana,23,Bogotá
3,Carlos,35,Medellín
4,Luis,30,Cali


In [ ]:
dfn = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'nombre': [' Ana', 'LUIS ', 'Carlos', 'ana'],
    'edad': [23, 30, 35, 28],
    'salario': [1000, 2000, 3000, 1500],
    'ciudad': ['Bogotá', 'Cali', 'Bogotá', 'Medellín']
})
dfn

,id,nombre,edad,salario,ciudad
0,1,Ana,23,1000,Bogotá
1,2,LUIS,30,2000,Cali
2,3,Carlos,35,3000,Bogotá
3,4,ana,28,1500,Medellín


In [ ]:
dfn["salario_anual"] = dfn["salario"] * 12
dfn["edad_doble"] = dfn["edad"].apply(lambda x: x *2)
dfn

,id,nombre,edad,salario,ciudad,salario_anual,edad_doble
0,1,Ana,23,1000,Bogotá,12000,46
1,2,LUIS,30,2000,Cali,24000,60
2,3,Carlos,35,3000,Bogotá,36000,70
3,4,ana,28,1500,Medellín,18000,56


In [ ]:
dfn = dfn.rename(columns={'edad': 'age'})
dfn

,id,nombre,ega,salario,ciudad,salario_anual,edad_doble
0,1,Ana,23,1000,Bogotá,12000,46
1,2,LUIS,30,2000,Cali,24000,60
2,3,Carlos,35,3000,Bogotá,36000,70
3,4,ana,28,1500,Medellín,18000,56


In [ ]:
dfn["nombre"] = dfn["nombre"].str.upper()
dfn["nombre"] = dfn["nombre"].str.strip()
dfn["nombre"] = dfn["nombre"].str.capitalize()
dfn

,id,nombre,ega,salario,ciudad,salario_anual,edad_doble
0,1,Ana,23,1000,Bogotá,12000,46
1,2,Luis,30,2000,Cali,24000,60
2,3,Carlos,35,3000,Bogotá,36000,70
3,4,Ana,28,1500,Medellín,18000,56


In [ ]:
grupo = dfn.groupby("ciudad")["salario"].mean()
grupo


,salario
ciudad,
Bogotá,2000.0
Cali,2000.0
Medellín,1500.0


In [ ]:
ordenado = dfn.sort_values(by="ega")
ordenado

,id,nombre,ega,salario,ciudad,salario_anual,edad_doble
0,1,Ana,23,1000,Bogotá,12000,46
3,4,Ana,28,1500,Medellín,18000,56
1,2,Luis,30,2000,Cali,24000,60
2,3,Carlos,35,3000,Bogotá,36000,70


In [ ]:

dfn1 = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'departamento': ['Ventas', 'IT', 'RRHH', 'Marketing']
})


In [ ]:
valores = dfn.values
valores

array([[1, ' Ana', 23, 1000, 'Bogotá'],
       [2, 'LUIS ', 30, 2000, 'Cali'],
       [3, 'Carlos', 35, 3000, 'Bogotá'],
       [4, 'ana', 28, 1500, 'Medellín']], dtype=object)

In [ ]:
arr = np.array([10, 20, 30])
df = pd.DataFrame(arr)
df

,0
0,10
1,20
2,30
